# GitHub Repository Default Settings
# Use this as a template when creating new repositories

default_branch: main

branch_protection:
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
  enforce_admins: false
  required_conversation_resolution: true
  allow_force_pushes: false
  allow_deletions: false

repository_settings:
  delete_branch_on_merge: true
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: true
  allow_update_branch: true

# Suggested .gitignore patterns for all repos
gitignore_patterns:
  - "*.code-workspace"
  - "*.swp"
  - "*.swo"
  - "*~"
  - ".DS_Store"
  - ".vscode/"
  - ".idea/"
  - "__pycache__/"
  - "*.pyc"
  - ".env"
  - ".env.local"
  - "node_modules/"
